<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container62xrvTe\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container62xrvTe/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container62xrvTe.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container62xrvTe\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container62xrvTe\App_KernelDevDebugContainer([
    'container.build_hash' => '62xrvTe',
    'container.build_id' => '5e71d082',
    'container.build_time' => 1686844770,
], __DIR__.\DIRECTORY_SEPARATOR.'Container62xrvTe');
