<?php

namespace ContainerAg3fGu6;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getJezekControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\JezekController' shared autowired service.
     *
     * @return \App\Controller\JezekController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/BaseController.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/JezekController.php';

        $container->services['App\\Controller\\JezekController'] = $instance = new \App\Controller\JezekController();

        $instance->setContainer(($container->privates['.service_locator.CshazM0'] ?? $container->load('get_ServiceLocator_CshazM0Service'))->withContext('App\\Controller\\JezekController', $container));

        return $instance;
    }
}
